Repository framgia/sph-solidity, pull requests merged in 2023-06, with the labels that each got.

#2 SOL-3 Create BE Project Environment
  .vscode/extensions.json
  package.json
  smart_contract/.gitignore
  smart_contract/.solhint.json
  smart_contract/.solhintignore
  smart_contract/README.md
  smart_contract/contracts/Lock.sol
  smart_contract/hardhat.config.ts
  smart_contract/package-lock.json
  smart_contract/package.json
  smart_contract/scripts/deploy.ts
  smart_contract/test/Lock.ts
  smart_contract/tsconfig.json
  smart_contract/yarn.lock
Labels: For Review

#3 SOL-14 [FE] Create markup for Header
  .gitignore
  fe/app.vue
  fe/src/assets/css/tailwind.css
  fe/src/components/base/button.vue
  fe/src/components/icons/BlocksLeft.vue
  fe/src/components/icons/BlocksRight.vue
  fe/src/layouts/default.vue
  fe/src/pages/index.vue
  fe/tailwind.config.js
Labels: For Review, Approved by Jason, Approved by Kent

#4 SOL-7 [FE] Create markup for navigation bar
  fe/nuxt.config.ts
  fe/package.json
  fe/src/assets/css/tailwind.css
  fe/src/components/Navbar.vue
  fe/src/components/WalletButton.vue
  fe/src/components/base/Search.vue
  fe/src/components/icons/Logo.vue
  fe/src/layouts/default.vue
  output.css
  package-lock.json
  package.json
  yarn.lock
Labels: Approved by John Paul, Approved by Kent

#6 SOL-11 [FE] Create markup for campaign creation
  .vscode/settings.json
  fe/nuxt.config.ts
  fe/package.json
  fe/src/assets/css/tailwind.css
  fe/src/assets/img/be-the-change.jpg
  fe/src/components/Navbar.vue
  fe/src/components/base/button.vue
  fe/src/components/base/input.vue
  fe/src/components/base/text-area.vue
  fe/src/components/file-upload.vue
  fe/src/layouts/default.vue
  fe/src/pages/create-campaign.vue
  fe/src/pages/index.vue
  fe/src/schemas/create-campaign.ts
  fe/tailwind.config.js
  package-lock.json
  yarn.lock
Labels: Approved by John Paul, Approved by Kent

#5 [SOL-15] [FE] Created Pagination, Footer, Campaign Card for Landing Page body
  .vscode/settings.json
  fe/src/assets/css/tailwind.css
  fe/src/components/base/campaign-card.vue
  fe/src/components/base/paginator.vue
  fe/src/components/file-upload.vue
  fe/src/components/global/footer.vue
  fe/src/components/icons/copy-right.vue
  fe/src/composables/useUtils.ts
  fe/src/layouts/default.vue
  fe/src/mocks/card-sample.json
  fe/src/pages/index.vue
  fe/src/types/CampaignCardProps.ts
  fe/src/types/PaginatorProps.ts
  fe/tailwind.config.js
Labels: Approved by Jason, Approved by Kent

#9 SOL-30 Update readme for documentation
  .env.example
  README.md
  fe/README.md
  package.json
  smart_contract/README.md
  smart_contract/package.json
Labels: For Review

#13 Fix End of Line issue
  .husky/pre-commit
  .lintstagedrc.json
  .prettierrc.json
  fe/.eslintrc.js
  fe/nuxt.config.ts
  fe/src/components/base/dropdown.vue
  fe/src/components/base/input.vue
  fe/src/components/base/text-area.vue
  fe/src/pages/create-campaign.vue
  fe/src/schemas/create-campaign.ts
  fe/tailwind.config.js
  prettierrc.json
Labels: Approved by John Paul, Approved by Keno

#8 SOL-9 [Integrate] Integrate metamask wallet in dApp
  .gitignore
  fe/.gitignore
  fe/nuxt.config.ts
  fe/package.json
  fe/src/components/Navbar.vue
  fe/src/components/WalletButton.vue
  fe/src/pages/create-campaign.vue
  fe/src/pages/dashboard.vue
  fe/src/plugins/toastify.ts
  fe/src/store/wallet.ts
  fe/tsconfig.json
  prettierrc.json
Labels: Approved by Arden, Approved by Wylen, Approved by Kent

#11 SOL-25 [Setup] Setup SunCI in github
  .sun-ci.yml
  fe/.eslintrc.js
  fe/package.json
  package-lock.json
  package.json
  yarn.lock
Labels: For Review, Approved by John Paul, Approved by Keno

#12 [SOL-36] [FE] Create markup for viewing only the user's campaigns
  fe/src/assets/css/tailwind.css
  fe/src/components/WalletButton.vue
  fe/src/components/base/tabs.vue
  fe/src/components/base/user-card.vue
  fe/src/mocks/user-card-sample.json
  fe/src/pages/create-campaign.vue
  fe/src/pages/profile.vue
  fe/src/types/TabsProps.ts
  fe/src/types/UserCardProps.ts
  yarn.lock
Labels: For Review, Approved by John Paul, Approved by Wylen, Approved by Kent

#10 SOL-13 [Integrate] Integrate smart contract function for creating campaign
  .lintstagedrc.json
  README.md
  fe/.eslintrc.js
  fe/nuxt.config.ts
  fe/package-lock.json
  fe/src/assets/contract/CrowdFunding.json
  fe/src/components/WalletButton.vue
  fe/src/components/base/button.vue
  fe/src/components/base/tabs.vue
  fe/src/pages/create-campaign.vue
  fe/src/pages/profile.vue
  fe/src/plugins/ethers.ts
  fe/src/schemas/create-campaign.ts
  fe/yarn.lock
  package-lock.json
  package.json
  smart_contract/README.md
  smart_contract/contracts/CrowdFunding.sol
  smart_contract/hardhat.config.ts
  smart_contract/package.json
  smart_contract/scripts/deploy.ts
  smart_contract/scripts/interact.ts
Labels: Approved by John Paul, Approved by Wylen, Approved by Kent, Approved by Keno
