Repository framgia/sph-solidity, pull requests merged in 2023-08, with the labels that each got.

#53 SOL-91 [Bugfix] There is an error toast display if invalid URL in the campaign details page
  fe/src/assets/contract/CrowdFunding.json
  fe/src/components/base/input.vue
  fe/src/components/base/text-area.vue
  fe/src/components/global/loader.vue
  fe/src/composables/useUtils.ts
  fe/src/error.vue
  fe/src/pages/campaigns/[id].vue
  fe/src/pages/campaigns/index.vue
  fe/src/pages/edit-campaign/[id].vue
  fe/src/pages/index.vue
  fe/src/plugins/ethers.ts
  fe/src/store/wallet.ts
  smart_contract/contracts/CrowdFunding.sol
Labels: For Review, Approved by Kent

#54 SOL-90 - [BE] - Create Smart Contract function for disbursement of funds: Success and Refund
  fe/src/assets/contract/CrowdFunding.json
  fe/src/assets/img/first-step.png
  fe/src/assets/img/placeholder.png
  fe/src/assets/img/second-step.png
  fe/src/assets/img/third-step.png
  fe/src/components/base/input.vue
  fe/src/components/campaign/fund-form.vue
  fe/src/components/global/wallet-button.vue
  fe/src/components/user/donations.vue
  fe/src/composables/useUtils.ts
  fe/src/pages/campaigns/[id].vue
  fe/src/pages/campaigns/index.vue
  fe/src/pages/help.vue
  fe/src/pages/index.vue
  fe/src/pages/profile.vue
  fe/src/plugins/ethers.ts
  fe/src/types/CampaignFundFormProps.ts
  fe/src/types/SmartContract.ts
  smart_contract/contracts/CrowdFunding.sol
  smart_contract/hardhat.config.ts
Labels: For Review, Approved by Kent

#55 [Hotfix] - Show view more button in home page
  fe/src/pages/index.vue
Labels: Approved by Arden, Approved by Wylen

#56 SOL-92 - Fix fetching recent campaigns and all campaigns
  fe/src/assets/contract/CrowdFunding.json
  fe/src/pages/campaigns/index.vue
  fe/src/pages/index.vue
  fe/src/plugins/ethers.ts
  fe/src/store/wallet.ts
  smart_contract/contracts/CrowdFunding.sol
Labels: Approved by Arden, Approved by Wylen

#57 SOL-94 [Improvement] User should not be able to access Edit Campaign if he/she is not the campaign creator
  fe/src/composables/useUtils.ts
  fe/src/pages/edit-campaign/[id].vue
Labels: For Review, Code Review: John Paul, Code Review: Wylen

#58 [Improvement] Opened tab in Profile page should persist after refreshing
  fe/src/components/base/tabs.vue
  fe/src/components/user/donations.vue
  fe/src/pages/index.vue
  fe/src/pages/profile.vue
Labels: Approved by Wylen, Approved by Kent

#59 SOL-93 Improve user experience for Create Campaign
  fe/src/pages/create-campaign.vue
Labels: For Review, Approved by John Paul, Approved by Kent

#60 [Bug] - Fix claim refund bug showing error after claiming the refund amount
  fe/src/pages/campaigns/[id].vue
Labels: Approved by Wylen

#61 SOL-97 [Improvement] Set Profile default active tab to My Campaigns
  fe/src/pages/profile.vue
Labels: For Review, Code Review: John Paul

#62 [Improvement] - Filter out multiple donators on the list of donators
  fe/src/assets/contract/CrowdFunding.json
  fe/src/components/user/donations.vue
  fe/src/components/user/donators.vue
  fe/src/composables/useUtils.ts
  fe/src/pages/profile.vue
  fe/src/plugins/ethers.ts
  fe/src/store/wallet.ts
  fe/src/types/DonatorsData.ts
  smart_contract/contracts/CrowdFunding.sol
Labels: Approved by Wylen
