Repository framgia/sph-solidity, pull requests merged in 2023-07, with the labels that each got.

#14 SOL-31 [FE] Create markup for update campaign page
  fe/src/assets/css/tailwind.css
  fe/src/components/Navbar.vue
  fe/src/components/WalletButton.vue
  fe/src/components/base/Search.vue
  fe/src/components/base/paginator.vue
  fe/src/layouts/default.vue
  fe/src/pages/create-campaign.vue
  fe/src/pages/edit-campaign.vue
  fe/src/pages/index.vue
  fe/src/plugins/ethers.ts
  prettierrc.json
Labels: Approved by John Paul, Approved by Kent, Approved by Keno

#15 SOL-37 [BE] Create smart contract function for viewing only the user's campaigns
  fe/src/assets/contract/CrowdFunding.json
  smart_contract/contracts/CrowdFunding.sol
  smart_contract/scripts/createCampaign.ts
  smart_contract/scripts/createContract.ts
  smart_contract/scripts/getUserCampaigns.ts
Labels: Approved by John Paul, Approved by Wylen, Approved by Kent

#16 SOL-41 [FE] Create markup for viewing specific campaign
  fe/.eslintrc.js
  fe/src/assets/css/tailwind.css
  fe/src/components/base/dropdown.vue
  fe/src/components/base/file-upload.vue
  fe/src/components/base/search-bar.vue
  fe/src/components/campaign/campaign-card.vue
  fe/src/components/campaign/content.vue
  fe/src/components/campaign/detail-card.vue
  fe/src/components/campaign/fund-form.vue
  fe/src/components/global/footer.vue
  fe/src/components/global/navbar.vue
  fe/src/components/global/wallet-button.vue
  fe/src/components/icons/blocks-left.vue
  fe/src/components/icons/blocks-right.vue
  fe/src/components/user/user-avatar.vue
  fe/src/components/user/user-card.vue
  fe/src/composables/useUtils.ts
  fe/src/mocks/campaign-sample.json
  fe/src/pages/campaigns/[id].vue
  fe/src/pages/create-campaign.vue
  fe/src/pages/index.vue
  fe/src/pages/profile.vue
  fe/src/schemas/fund-campaign.ts
  fe/src/types/CampaignProps.ts
Labels: Approved by Arden, Approved by Kent, Approved by Keno

#18 SOL-45 [FE] Create markup for viewing donators on user campaign
  fe/src/components/base/paginator.vue
  fe/src/components/campaign/card.vue
  fe/src/components/campaign/content.vue
  fe/src/components/user/avatar.vue
  fe/src/components/user/campaigns.vue
  fe/src/components/user/card.vue
  fe/src/components/user/donators.vue
  fe/src/components/user/user-avatar.vue
  fe/src/composables/useUtils.ts
  fe/src/mocks/campaign-donators.json
  fe/src/pages/create-campaign.vue
  fe/src/pages/index.vue
  fe/src/pages/profile.vue
  fe/src/types/PaginatorProps.ts
Labels: For Review, Code Review: Wylen, Approved by Kent, Approved by Keno

#17 SOL-33 [BE] Create smart contract function for updating campaign
  fe/src/assets/contract/CrowdFunding.json
  smart_contract/contracts/CrowdFunding.sol
  smart_contract/scripts/createCampaign.ts
  smart_contract/scripts/editCampaign.ts
Labels: Approved by Wylen, Approved by Kent

#20 SOL-56 [BE] Implement pagination for viewing user's campaigns
  fe/src/assets/contract/CrowdFunding.json
  smart_contract/contracts/CrowdFunding.sol
  smart_contract/contracts/Lock.sol
  smart_contract/scripts/getUserCampaigns.ts
Labels: Approved by John Paul, Approved by Wylen, Approved by Kent

#21 SOL-50 [BE] Create smart contract function for sending donation to a campaign
  fe/src/assets/contract/CrowdFunding.json
  smart_contract/contracts/CrowdFunding.sol
  smart_contract/scripts/createContract.ts
  smart_contract/scripts/getUserCampaigns.ts
  smart_contract/scripts/sendDonation.ts
Labels: Approved by John Paul, Approved by Wylen, Approved by Kent

#19 SOL-38 [Integrate] Integrate smart contract function for viewing only their campaigns
  fe/src/components/campaign/card.vue
  fe/src/components/user/campaigns.vue
  fe/src/composables/useUtils.ts
  fe/src/mocks/user-card-sample.json
  fe/src/pages/campaigns/[id].vue
  fe/src/pages/create-campaign.vue
  fe/src/pages/edit-campaign.vue
  fe/src/pages/profile.vue
  fe/src/types/CampaignCardProps.ts
  fe/src/types/UserCardProps.ts
Labels: For Review, Approved by Arden, Approved by Kent

#22 SOL-57 [Improvement] Add required Metamask, title and icon
  README.md
  fe/nuxt.config.ts
  fe/public/favicon.ico
  fe/src/assets/img/logo-asterisk.png
  fe/src/assets/img/logo.png
  fe/src/pages/create-campaign.vue
  fe/src/plugins/ethers.ts
  fe/src/public/favicon.ico
  smart_contract/README.md
Labels: Approved by Chevy, Approved by Jason, Approved by Wylen, Approved by Kent

#25 SOL-51 [Integrate] Integrate smart contract function for sending donation to a campaign
  fe/src/components/campaign/card.vue
  fe/src/components/campaign/fund-form.vue
  fe/src/components/user/campaigns.vue
  fe/src/pages/campaigns/[id].vue
  fe/src/plugins/ethers.ts
  fe/src/schemas/fund-campaign.ts
  fe/src/types/CampaignCardProps.ts
  fe/src/types/CampaignFundFormProps.ts
Labels: For Review, Approved by Chevy, Approved by Wylen, Approved by Kent

#23 SOL-52 [BE] Create smart contract function for viewing specific campaign
  fe/src/assets/contract/CrowdFunding.json
  fe/src/plugins/ethers.ts
  smart_contract/contracts/CrowdFunding.sol
  smart_contract/scripts/getCampaign.ts
  smart_contract/scripts/getCampaignDonations.ts
Labels: For Review, Approved by Arden, Approved by John Paul, Approved by Kent

#26 SOL-46 [BE] Create smart contract function for viewing donators on user's campaigns
  fe/src/assets/contract/CrowdFunding.json
  fe/src/plugins/ethers.ts
  smart_contract/README.md
  smart_contract/contracts/CrowdFunding.sol
  smart_contract/scripts/createContract.ts
  smart_contract/scripts/getDonatorsByWalletAddress.ts
Labels: Approved by Arden, Approved by Wylen, Approved by Kent

#28 After sending donation 2 toast displays
  fe/src/plugins/ethers.ts
Labels: Approved by Wylen, Approved by Kent, Approved by Keno

#29 SOL-61 [FE] Show modal for first time user and pages on how to instal…
  fe/src/assets/css/tailwind.css
  fe/src/assets/img/fund-sepolia-wallet.png
  fe/src/assets/img/metamask-extension.png
  fe/src/assets/img/select-sepolia-test-network.png
  fe/src/assets/img/toggle-test-networks.png
  fe/src/components/base/modal.vue
  fe/src/components/global/navbar.vue
  fe/src/components/global/wallet-button.vue
  fe/src/components/help/setup.vue
  fe/src/pages/campaigns/[id].vue
  fe/src/pages/create-campaign.vue
  fe/src/pages/edit-campaign.vue
  fe/src/pages/help.vue
  fe/src/pages/index.vue
  fe/src/store/wallet.ts
Labels: For Review, Code Review: John Paul, Approved by Kent, Approved by Keno

#30 SOL-63 [BE] Create smart contract function for viewing user's donations on all campaigns
  fe/src/assets/contract/CrowdFunding.json
  fe/src/plugins/ethers.ts
  package-lock.json
  smart_contract/README.md
  smart_contract/contracts/CrowdFunding.sol
  smart_contract/package.json
  smart_contract/scripts/createCampaign.ts
  smart_contract/scripts/editCampaign.ts
  smart_contract/scripts/getCampaign.ts
  smart_contract/scripts/getCampaignDonations.ts
  smart_contract/scripts/getDonatorsByWalletAddress.ts
  smart_contract/scripts/getUserCampaigns.ts
  smart_contract/scripts/getUserDonations.ts
  smart_contract/scripts/interact.ts
  smart_contract/scripts/sendDonation.ts
Labels: For Review, Code Review: John Paul, Approved by Wylen, Approved by Kent

#31 SOL-34 [Integrate] Integrate smart contract function for updating campaign
  fe/src/components/campaign/content.vue
  fe/src/components/campaign/fund-form.vue
  fe/src/composables/useUtils.ts
  fe/src/pages/campaigns/[id].vue
  fe/src/pages/create-campaign.vue
  fe/src/pages/edit-campaign.vue
  fe/src/pages/edit-campaign/[id].vue
  fe/src/plugins/ethers.ts
Labels: Approved by Arden, Approved by Wylen, Approved by Kent

#33 SOL-47 [Integrate] Integrate smart contract function for viewing donators on user's campaigns
  fe/src/components/user/donators.vue
  fe/src/composables/useUtils.ts
  fe/src/pages/profile.vue
  fe/src/plugins/ethers.ts
  fe/src/types/DonatorsData.ts
Labels: For Review, Approved by Arden, Approved by Jason, Approved by Kent

#34 SOL-71 [FE] Implement route protection
  fe/src/components/campaign/content.vue
  fe/src/components/global/wallet-button.vue
  fe/src/middleware/auth.ts
  fe/src/pages/campaigns/[id].vue
  fe/src/pages/edit-campaign.vue
  fe/src/pages/profile.vue
Labels: Approved by Arden, Approved by John Paul, Approved by Kent

#36 SOL-53 [Integrate] Integrate smart contract function for viewing specific campaigns
  fe/src/components/campaign/content.vue
  fe/src/pages/campaigns/[id].vue
  fe/src/pages/edit-campaign.vue
  fe/src/plugins/ethers.ts
  fe/src/types/Campaign.ts
  fe/src/types/SmartContract.ts
  smart_contract/scripts/getCampaign.ts
  smart_contract/scripts/getCampaignDonations.ts
Labels: For Review, Approved by Arden, Approved by John Paul, Approved by Kent, Approved by Keno

#37 SOL-70 [BE] Create smart contract function to search by campaign title
  fe/src/assets/contract/CrowdFunding.json
  fe/src/plugins/ethers.ts
  smart_contract/README.md
  smart_contract/contracts/CrowdFunding.sol
  smart_contract/scripts/interact.ts
  smart_contract/scripts/searchByTitle.ts
Labels: Approved by John Paul, Approved by Wylen, Approved by Kent

#42 SOL-81 [Bugfix] add placeholder for tables
  fe/src/components/campaign/card.vue
  fe/src/components/user/campaigns.vue
  fe/src/components/user/donations.vue
  fe/src/components/user/donators.vue
  fe/src/pages/campaigns/[id].vue
Labels: For Review, Approved by John Paul, Approved by Wylen, Approved by Kent

#43 SOL-82 [Bugfix] Remove error toast in the Donations Tab
  fe/src/components/user/campaigns.vue
  fe/src/components/user/donations.vue
  fe/src/pages/profile.vue
Labels: For Review, Approved by John Paul, Approved by Kent

#39 SOL-67 [Integrate] Integrate smart contract function for viewing recent campaigns in landing page
  fe/src/components/campaign/card.vue
  fe/src/pages/index.vue
  fe/src/plugins/ethers.ts
  fe/src/store/wallet.ts
  fe/src/types/CampaignCardProps.ts
  fe/src/types/RecentCampaignData.ts
  smart_contract/scripts/getRecentCampaigns.ts
Labels: Approved by Arden, Approved by Wylen, Approved by Kent

#45 SOL-86 [Bugfix] fix bug on disappearing paginator and update items pe…
  fe/src/components/campaign/card.vue
  fe/src/components/user/campaigns.vue
  fe/src/components/user/donations.vue
  fe/src/components/user/donators.vue
  fe/src/pages/profile.vue
Labels: Approved by Arden, Approved by John Paul, Approved by Kent

#44 SOL-79 [BE] Update smart contract functions to include image
  fe/src/assets/contract/CrowdFunding.json
  fe/src/plugins/ethers.ts
  smart_contract/README.md
  smart_contract/contracts/CrowdFunding.sol
  smart_contract/scripts/createCampaign.ts
  smart_contract/scripts/editCampaign.ts
  smart_contract/scripts/interact.ts
Labels: Approved by Arden, Approved by Wylen, Approved by Kent

#46 SOL-74 [Integrate] Integrate smart contract function for viewing all campaigns
  fe/src/components/campaign/card-view.vue
  fe/src/components/campaign/table-view.vue
  fe/src/components/user/campaigns.vue
  fe/src/pages/campaigns/index.vue
  fe/src/pages/index.vue
  fe/src/types/Campaign.ts
  fe/src/types/SmartContract.ts
Labels: Approved by Arden, Approved by John Paul, Approved by Kent

#49 SOL-80 [Integrate] Update FE to include image when viewing, creating,…
  fe/nuxt.config.ts
  fe/src/assets/img/placeholder.png
  fe/src/components/base/input.vue
  fe/src/components/campaign/card-view.vue
  fe/src/components/campaign/card.vue
  fe/src/components/user/campaigns.vue
  fe/src/mocks/campaing-card-array-sample.json
  fe/src/pages/campaigns/[id].vue
  fe/src/pages/campaigns/index.vue
  fe/src/pages/create-campaign.vue
  fe/src/pages/edit-campaign/[id].vue
  fe/src/pages/index.vue
  fe/src/pages/profile.vue
  fe/src/plugins/isImageUrl.ts
  fe/src/public/placeholder.png
  fe/src/schemas/create-campaign.ts
  fe/src/store/wallet.ts
  fe/src/types/Campaign.ts
  fe/src/types/CampaignCardProps.ts
  fe/src/types/RecentCampaignData.ts
  fe/src/types/SmartContract.ts
  fe/tailwind.config.js
Labels: For Review, Code Review: John Paul, Approved by Wylen, Approved by Kent

#48 SOL-69 [Integrate] Integrate search function in FE
  fe/src/assets/contract/CrowdFunding.json
  fe/src/components/base/search-bar.vue
  fe/src/components/campaign/content.vue
  fe/src/components/campaign/table-view.vue
  fe/src/components/global/navbar.vue
  fe/src/composables/useUtils.ts
  fe/src/pages/campaigns/[id].vue
  fe/src/pages/campaigns/index.vue
  fe/src/plugins/ethers.ts
  fe/src/types/Campaign.ts
  smart_contract/contracts/CrowdFunding.sol
  smart_contract/scripts/createCampaign.ts
  smart_contract/scripts/editCampaign.ts
  smart_contract/scripts/getAllCampaigns.ts
  smart_contract/scripts/getCampaign.ts
  smart_contract/scripts/getCampaignDonations.ts
  smart_contract/scripts/getRecentCampaigns.ts
  smart_contract/scripts/getUserCampaigns.ts
  smart_contract/scripts/getUserDonations.ts
  smart_contract/scripts/interact.ts
  smart_contract/scripts/searchByTitle.ts
Labels: Approved by Arden, Approved by John Paul, Approved by Kent

#47 SOL-85 - [Improvement] - Implement real-time updates on other pages.
  fe/src/components/global/loader.vue
  fe/src/components/user/campaigns.vue
  fe/src/components/user/donations.vue
  fe/src/components/user/donators.vue
  fe/src/pages/campaigns/[id].vue
  fe/src/pages/campaigns/index.vue
  fe/src/pages/create-campaign.vue
  fe/src/pages/edit-campaign/[id].vue
  fe/src/pages/index.vue
  fe/src/pages/profile.vue
  fe/src/plugins/ethers.ts
  fe/src/store/wallet.ts
  fe/src/types/Campaign.ts
Labels: For Review, Approved by Arden, Approved by Wylen, Approved by Kent

#52 SOL-87 [Improvement] Update setups page and campaign cards
  fe/nuxt.config.ts
  fe/src/components/base/button.vue
  fe/src/components/campaign/table-view.vue
  fe/src/components/global/navbar.vue
  fe/src/components/help/setup.vue
  fe/src/composables/useUtils.ts
  fe/src/pages/create-campaign.vue
  fe/src/pages/edit-campaign/[id].vue
  fe/src/pages/help.vue
  fe/src/plugins/ethers.ts
  fe/src/utils/isImageUrl.ts
Labels: Approved by Arden, Approved by Wylen, Approved by Kent

#51 SOL-89 - [Improvement] - Enhance Campaign Visibility and Filtering on Index Page
  fe/src/assets/contract/CrowdFunding.json
  fe/src/components/base/input.vue
  fe/src/components/base/text-area.vue
  fe/src/components/campaign/content.vue
  fe/src/components/campaign/fund-form.vue
  fe/src/components/global/wallet-button.vue
  fe/src/components/user/campaigns.vue
  fe/src/composables/useUtils.ts
  fe/src/pages/campaigns/[id].vue
  fe/src/pages/edit-campaign/[id].vue
  fe/src/plugins/ethers.ts
  fe/src/types/CampaignFundFormProps.ts
  fe/src/types/SmartContract.ts
  smart_contract/contracts/CrowdFunding.sol
Labels: Approved by Wylen, Approved by Kent
